[package]
name = "gango"
version = "0.0.1"
authors = ["Graf_Blutwurst"]
edition = "2018"

[dependencies]
tui = "0.16.0"
termion = "1.5.6"
serde = {version = "1.0.130", features = ["derive"]}
serde_json = "1.0.68"